apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ctc209w9j-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ctc209w9j-nodejs 
  name: ctc209w9j-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: ctc209w9j-nodejs 
